#!/usr/bin/env bash

# shellcheck disable=SC2155

set -Eeuo pipefail
trap 'echo_error Program exited with status ${?}' ERR

# Arguments
readonly FLAG="${1:-}"

echo_error()
{
    echo "$(tput setaf 1)${*}$(tput sgr0)"
}

main()
{
    readonly PURGE_LIST=$(dpkg -l | grep '^rc' | awk '{print $2}' || true)

    if [ -n "${PURGE_LIST}" ]; then
        echo "Packages to purge:"
        echo -e "${PURGE_LIST}"
        echo

        if [ "${FLAG}" = "-x" ]; then
            # shellcheck disable=SC2086
            sudo dpkg --purge ${PURGE_LIST}
        else
            echo "Run with -x to actually execute the purging"
        fi
    else
        echo "No packages with residual config"
    fi
}

main
