#!/usr/bin/env bash

set -Eeuo pipefail
trap 'echo_error "\e[1mError: program exited with status ${?} at line ${LINENO}"' ERR

# Arguments
readonly URL="${1}"
readonly DIST="${2}"
readonly REPO="${3}"
readonly ARCH="${4:-$(dpkg --print-architecture)}"

echo_error()
{
    echo -e "\e[0;31m${*}\e[0m"
}

main()
{
    curl -fsSL "${URL}/dists/${DIST}/${REPO}/binary-${ARCH}/Packages.gz" \
    | gunzip \
    | grep '^Package' \
    | awk '{print $2}' \
    | sort -u
}

main
