#!/usr/bin/env bash

set -Eeu
trap 'echo "Error: ${SCRIPT} - Function: ${FUNCNAME:-global context} - Line: ${LINENO} - Status: ${?}"' ERR

# Arguments
# shellcheck disable=SC2155
readonly SCRIPT=$(basename "${0}")
readonly FLAG="${1:-}"

main()
{
    # shellcheck disable=SC2155
    readonly PURGE_LIST=$(dpkg -l | grep '^rc' | awk '{print $2}' || true)

    if [ -n "${PURGE_LIST}" ]; then
        echo "Packages to purge:"
        echo -e "${PURGE_LIST}"
        echo

        if [ "${FLAG}" = "-x" ]; then
            # shellcheck disable=SC2086
            sudo dpkg --purge ${PURGE_LIST}
        else
            echo "Run with -x to actually execute the purging"
        fi
    else
        echo "No packages with residual config"
    fi
}

main
