#!/usr/bin/env bash

set -Eeuo pipefail
trap 'echo_error "\e[1mError: program exited with status ${?} at line ${LINENO}"' ERR

# Arguments
readonly AWS_PROFILE_ARG="${1:-}"

echo_error()
{
    echo -e "\e[0;31m${*}\e[0m"
}

main()
{
    if [ -z "${AWS_PROFILE:-}" ]; then
        if [ -z "${AWS_PROFILE_ARG}" ]; then
            echo_error "An AWS profile must be passed as argument or set via the AWS_PROFILE environment variable"
            exit 1
        else
            readonly AWS_PROFILE="${AWS_PROFILE_ARG}"
            export AWS_PROFILE
        fi
    fi

    ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
    REGION="$(aws configure get region)"
    readonly ECR_DOMAIN="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"

    aws ecr get-login-password | docker login --username AWS --password-stdin "${ECR_DOMAIN}"
}

main
