#!/usr/bin/env bash

readonly ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
readonly REGION="$(aws configure get region)"
readonly ECR_DOMAIN="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"

aws ecr get-login-password | docker login --username AWS --password-stdin "${ECR_DOMAIN}"
