#!/usr/bin/env bash

set -Eeuo pipefail
trap 'echo_error "\e[1mError: program exited with status ${?} at line ${LINENO}"' ERR

# Arguments
# shellcheck disable=SC2155
readonly SCRIPT=$(basename "${0}")
readonly AWS_PROFILE_NAME="${1:-}"
readonly USER_POOL_ID="${2:-}"

echo_error()
{
    echo -e "\e[0;31m${*}\e[0m"
}

print_usage()
{
    echo
    echo "Usage: ${SCRIPT} <aws_profile> [user_pool_id]"
    echo
    echo "aws_profile     Name of the aws profile."
    echo "user_pool_id    If specified, it shows the list of users in that pool."
    echo "                Otherwise it shows the list of user pools."
    echo
}

list_user_pools()
{
    echo
    aws cognito-idp list-user-pools \
        --profile "${AWS_PROFILE_NAME}" \
        --no-cli-pager \
        --max-results 50 \
        --query "UserPools[].{Name:Name, Id:Id}" \
        --output text | \
    column -t -o "    " | \
    sort -f -k 2
    echo
}

list_users()
{
    echo
    aws cognito-idp list-users \
        --profile "${AWS_PROFILE_NAME}" \
        --no-cli-pager \
        --user-pool-id "${USER_POOL_ID}" \
        --query "Users[].{Username:Username, UserStatus:UserStatus, Email:Attributes[?Name=='email'].Value | [0]}" \
        --output text | \
    column -t -o "    " -O "3,1,2" | \
    sort -f -k 2
    echo
}

main()
{
    if [ -z "${AWS_PROFILE_NAME}" ]; then
        print_usage
    elif [ -z "${USER_POOL_ID}" ]; then
        list_user_pools
    else
        list_users
    fi
}

main
