#!/usr/bin/env bash

set -Eeuo pipefail
trap 'echo_error "\e[1mError: program exited with status ${?} at line ${LINENO}"' ERR

# Arguments
readonly LEFT="${1:-}"
readonly RIGHT="${2:-}"

echo_error()
{
    echo -e "\e[0;31m${*}\e[0m"
}

main()
{
    diff -Naur "${LEFT}" "${RIGHT}" | diff-so-fancy
}

main
