#!/usr/bin/env bash

set -Eeu
trap 'echo "Error: ${SCRIPT} - Function: ${FUNCNAME:-global context} - Line: ${LINENO} - Status: ${?}"' ERR

# Arguments
# shellcheck disable=SC2155
readonly SCRIPT=$(basename "${0}")
readonly LEFT="${1:-}"
readonly RIGHT="${2:-}"

main()
{
    diff -Naur "${LEFT}" "${RIGHT}" | diff-so-fancy
}

main
