#!/usr/bin/env bash

set -Eeuo pipefail
trap 'echo_error Error: program exited with status ${?}' ERR

# Arguments
readonly SEARCH="${1}"

# Settings
readonly BASE_PATH="/"
readonly EXCLUDE_PATHS=(
    "${HOME}/dev/docker-data"
    "/run/user"
)

echo_error()
{
    echo "$(tput setaf 1)${*}$(tput sgr0)"
}

main()
{
    local EXCLUDE_ARGS=""

    for EXCLUDE_PATH in ${EXCLUDE_PATHS[*]}; do
        EXCLUDE_ARGS="${EXCLUDE_ARGS} -path ${EXCLUDE_PATH} -o"
    done

    EXCLUDE_ARGS="${EXCLUDE_ARGS:: -3}"

    # shellcheck disable=SC2086
    sudo find ${BASE_PATH} \( ${EXCLUDE_ARGS} \) -prune -o -iname "*${SEARCH}*" -print
}

main
