#!/usr/bin/env bash

set -Eeuo pipefail
trap 'echo_error "\e[1mError: program exited with status ${?} at line ${LINENO}"' ERR

# Arguments
readonly SEARCH="${1}"

# Settings
readonly BASE_PATH="/"
readonly EXCLUDE_PATHS=(
    "${HOME}/dev/docker-data"
    "/run/user"
    "/proc"
)

echo_error()
{
    echo -e "\e[0;31m${*}\e[0m"
}

main()
{
    local EXCLUDE_ARGS=""

    # shellcheck disable=SC2048
    for EXCLUDE_PATH in ${EXCLUDE_PATHS[*]}; do
        EXCLUDE_ARGS="${EXCLUDE_ARGS} -path ${EXCLUDE_PATH} -o"
    done

    EXCLUDE_ARGS="${EXCLUDE_ARGS:: -3}"

    # shellcheck disable=SC2086
    sudo find ${BASE_PATH} \( ${EXCLUDE_ARGS} \) -prune -o -iname "*${SEARCH}*" -print
}

main
