#!/usr/bin/env bash

set -Eeu
trap 'echo "Error: ${SCRIPT} - Function: ${FUNCNAME:-global context} - Line: ${LINENO} - Status: ${?}"' ERR

# Arguments
# shellcheck disable=SC2155
readonly SCRIPT=$(basename "${0}")
readonly SEARCH="${1}"

# Settings
readonly BASE_PATH="${HOME}"
readonly EXCLUDE_PATHS=(
    "${HOME}/dev/docker-data"
)

main()
{
    local EXCLUDE_ARGS=""

    # shellcheck disable=SC2048
    for EXCLUDE_PATH in ${EXCLUDE_PATHS[*]}; do
        EXCLUDE_ARGS="${EXCLUDE_ARGS:-} -path ${EXCLUDE_PATH} -o"
    done

    EXCLUDE_ARGS="${EXCLUDE_ARGS:: -3}"

    # shellcheck disable=SC2086
    find ${BASE_PATH} \( ${EXCLUDE_ARGS} \) -prune -o -iname "*${SEARCH}*" -print
}

main
