#!/usr/bin/env bash

set -Eeuo pipefail
trap 'echo_error Error: program exited with status ${?}' ERR

# Arguments
readonly SEARCH="${1}"

echo_error()
{
    echo "$(tput setaf 1)${*}$(tput sgr0)"
}

main()
{
    find "${HOME}" -iname "*${SEARCH}*" -print
}

main
