#!/usr/bin/env bash

set -Eeuo pipefail
trap 'echo_error Program exited with status ${?}' ERR

echo_error()
{
    echo "$(tput setaf 1)${*}$(tput sgr0)"
}

main()
{
    git init -b main .
    git commit --allow-empty --message 'Repo init'
}

main
