#!/usr/bin/env bash

set -Eeuo pipefail
trap 'echo_error Error: program exited with status ${?}' ERR

echo_error()
{
    echo -e "\e[0;31m${*}\e[0m"
}

main()
{
    git reflog expire --expire-unreachable=now --all
    git gc --prune=now
}

main
