#!/usr/bin/env bash

set -Eeuo pipefail
trap 'echo_error Program exited with status ${?}' ERR

echo_error()
{
    echo "$(tput setaf 1)${*}$(tput sgr0)"
}

main()
{
    git reflog expire --expire-unreachable=now --all
    git gc --prune=now
}

main
