#!/usr/bin/env bash

set -Eeuo pipefail
trap 'echo_error Error: program exited with status ${?}' ERR

echo_error()
{
    echo -e "\e[0;31m${*}\e[0m"
}

main()
{
    git init -b main .
    git commit --allow-empty --message 'Repo init'
}

main
