#!/usr/bin/env bash

set -Eeuo pipefail
trap 'echo_error "\e[1mError: program exited with status ${?} at line ${LINENO}"' ERR

# Arguments
readonly OPTION="${1:-}"

# Settings
readonly PACKAGES=(
    "@quasar/cli"
    "@vue/cli"
    "@vue/cli-service"
    "concurrently"
    "corepack"
    "create-react-app"
    "diff-so-fancy"
    "dockerfilelint"
    "editorconfig"
    "eslint"
    "express-generator"
    "gulp-cli"
    "list-repos"
    "markdownlint-cli"
    "nodemon"
    "npm"
    "npm-check-updates"
    "parcel"
    "pm2"
    "semver"
    "serve"
    "snowpack"
    "typescript"
    "webpack"
    "webpack-cli"
)

echo_info()
{
    echo -e "\e[0;36m${*}\e[0m"
}

echo_error()
{
    echo -e "\e[0;31m${*}\e[0m"
}

check_bin()
{
    if ! command -v "${1}" &> /dev/null; then
        echo -e "\e[0;31mError: \"${1}\" is required but not installed.\e[0m"
        exit 1
    fi
}

npm_install()
{
    for PACKAGE in "${PACKAGES[@]}"; do
        echo_info "Installing ${PACKAGE}"
        npm install --global "${PACKAGE}"
    done
}

npm_uninstall()
{
    local -r UN_PACKAGES="$(npm list --global --parseable --depth 0 | tail -n +2)"

    for PACKAGE in ${UN_PACKAGES}; do
        local PACKAGE=${PACKAGE#*node_modules/}
        if [ "${PACKAGE}" != "npm" ]; then
            echo_info "Uninstalling ${PACKAGE}"
            npm uninstall --global "${PACKAGE}"
        fi
    done
}

main()
{
    check_bin npm

    case ${OPTION} in
        '')
            npm_install
            ;;
        -u)
            npm_uninstall
            ;;
        *)
            echo "Unrecognized option \"${OPTION}\", use \"-u\" to uninstall the packages"
            ;;
    esac
}

main
