#!/usr/bin/env bash

# shellcheck disable=SC2155

set -Eeuo pipefail
trap 'print_error ${BASH_SOURCE[0]} ${LINENO} ${?}' ERR
trap 'print_report' EXIT

# Arguments
readonly SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"

# Settings
readonly BIN_DIR="${HOME}/dev/bin"
readonly TEMP_DIR="/tmp"

echo_info()
{
    echo "$(tput setaf 6)${*}$(tput sgr0)"
}

echo_error()
{
    echo "$(tput setaf 1)${*}$(tput sgr0)"
}

print_error()
{
    local -r SOURCE_PATH="${1}"
    local -r LINE_NUMBER="${2}"
    local -r EXIT_STATUS="${3}"
    local -r CONTEXT_LINES="3"
    local -r SOURCE_CODE="$(pr -tn "${SOURCE_PATH}")"

    local RELATIVE_PATH="${SOURCE_PATH#"${SCRIPT_DIR}"}"
    local -r RELATIVE_PATH="${RELATIVE_PATH#/}"

    echo
    echo_error "$(tput bold)Error: command exited with status ${EXIT_STATUS} at ${RELATIVE_PATH}:${LINE_NUMBER}"

    tail -n +$((LINE_NUMBER - CONTEXT_LINES)) <<< "${SOURCE_CODE}" | head -n ${CONTEXT_LINES}
    echo_error "$(tput bold)$(tail -n +$((LINE_NUMBER)) <<< "${SOURCE_CODE}" | head -n 1)"
    tail -n +$((LINE_NUMBER + 1)) <<< "${SOURCE_CODE}" | head -n ${CONTEXT_LINES}
    echo

    exit 1
}

check_bin()
{
    if ! command -v "${1}" &> /dev/null; then
        echo_error "Error: \"${1}\" is required but not installed."
        exit 1
    fi
}

get_latest_github_version()
{
    local -r PROJECT="${1}"
    local -r RELEASES="$(curl -sSL "https://api.github.com/repos/${PROJECT}/releases" | jq -r .[].tag_name | head -n 1)"

    # shellcheck disable=SC2086
    semver -r "" ${RELEASES} | tail -n 1
}

install_hashicorp_app()
{
    local -r APP="${1}"

    local APP_VERSION
    APP_VERSION="$(curl -s "https://checkpoint-api.hashicorp.com/v1/check/${APP}" | jq -r -M '.current_version')"
    APP_VERSION="${APP_VERSION/v/}"
    local -r APP_URL="https://releases.hashicorp.com/${APP}/${APP_VERSION}/${APP}_${APP_VERSION}_linux_amd64.zip"

    curl -sSL "${APP_URL}" -o "${TEMP_DIR}/${APP}.zip"

    unzip -q -o "${TEMP_DIR}/${APP}.zip" -d "${TEMP_DIR}"
    rm -f "${TEMP_DIR}/${APP}.zip"

    mv -f "${TEMP_DIR}/${APP}" "${BIN_DIR}/${APP}"
    chmod +x "${BIN_DIR}/${APP}"
}

install_bin()
{
    local -r URL="${1}"
    local -r BIN_NAME="${2}"

    curl -sSL "${URL}" -o "${BIN_DIR}/${BIN_NAME}"
    chmod +x "${BIN_DIR}/${BIN_NAME}"
}

install_targz()
{
    local -r URL="${1}"
    local -r SRC_BIN_PATH="${2}"
    local -r BIN_NAME="${3}"

    curl -sSL "${URL}" -o "${TEMP_DIR}/${BIN_NAME}.tar.gz"
    mkdir -p "${TEMP_DIR}/${BIN_NAME}"
    tar xzf "${TEMP_DIR}/${BIN_NAME}.tar.gz" -C "${TEMP_DIR}/${BIN_NAME}"
    mv -f "${TEMP_DIR}/${BIN_NAME}/${SRC_BIN_PATH}" "${BIN_DIR}/${BIN_NAME}"
    chmod +x "${BIN_DIR}/${BIN_NAME}"
    rm -rf "${TEMP_DIR:?}/${BIN_NAME}"
    rm -f "${TEMP_DIR}/${BIN_NAME}.tar.gz"
}

print_version()
{
    local -r BIN=${1}
    local OLD_VERSION=${2}
    local NEW_VERSION=${3}

    if [ -z "${OLD_VERSION}" ]; then
        OLD_VERSION="None"
    fi

    if [ -z "${NEW_VERSION}" ]; then
        NEW_VERSION="Error getting the new version"
    fi

    if [ "${OLD_VERSION}" = "${NEW_VERSION}" ]; then
        echo "${BIN}: ${NEW_VERSION}"
    else
        echo "$(tput setaf 3)${BIN}: ${OLD_VERSION} -> ${NEW_VERSION}$(tput sgr0)"
    fi
}

print_report()
{
    {
        print_version "ctop"           "${CTOP_VERSION_OLD}"      "${CTOP_VERSION_NEW}"
        print_version "docker-compose" "${COMPOSE_VERSION_OLD}"   "${COMPOSE_VERSION_NEW}"
        print_version "jfrog"          "${JFROG_VERSION_OLD}"     "${JFROG_VERSION_NEW}"
        print_version "terraform"      "${TERRAFORM_VERSION_OLD}" "${TERRAFORM_VERSION_NEW}"
        print_version "vagrant"        "${VAGRANT_VERSION_OLD}"   "${VAGRANT_VERSION_NEW}"
    } | column -t -s ' '
    echo
}

main()
{
    check_bin semver
    check_bin curl
    check_bin unzip
    check_bin tar
    check_bin gzip
    check_bin jq

    if [ ! -d "${BIN_DIR}" ]; then
        mkdir -p "${BIN_DIR}"
    fi

    echo
    echo_info "Installing binaries"

    # Install ctop
    echo "Installing ctop"
    readonly CTOP_VERSION_OLD="$(ctop -v 2> /dev/null | cut -d ' ' -f 3 | sed 's/.$//')"
    local -r CTOP_VERSION_LATEST="$(get_latest_github_version bcicen/ctop)"
    install_bin "https://github.com/bcicen/ctop/releases/download/v${CTOP_VERSION_LATEST}/ctop-${CTOP_VERSION_LATEST}-linux-amd64" \
        "ctop"
    readonly CTOP_VERSION_NEW="$(ctop -v 2> /dev/null | cut -d ' ' -f 3 | sed 's/.$//')"

    # Install docker-compose
    echo "Installing docker-compose"
    readonly COMPOSE_VERSION_OLD="$(docker-compose version 2> /dev/null | head -n 1 | cut -d ' ' -f 3 | sed 's/.$//')"
    local -r COMPOSE_VERSION_LATEST="$(get_latest_github_version docker/compose)"
    install_bin "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION_LATEST}/docker-compose-Linux-x86_64" \
        "docker-compose"
    readonly COMPOSE_VERSION_NEW="$(docker-compose version 2> /dev/null | head -n 1 | cut -d ' ' -f 3 | sed 's/.$//')"

    # Install jfrog
    echo "Installing jfrog"
    readonly JFROG_VERSION_OLD="$(jfrog -v 2> /dev/null | cut -d ' ' -f 3)"
    install_bin "https://api.bintray.com/content/jfrog/jfrog-cli-go/\$latest/jfrog-cli-linux-amd64/jfrog?bt_package=jfrog-cli-linux-amd64" \
        "jfrog"
    readonly JFROG_VERSION_NEW="$(jfrog -v 2> /dev/null | cut -d ' ' -f 3)"

    # Install terraform
    echo "Installing terraform"
    readonly TERRAFORM_VERSION_OLD="$(terraform -v 2> /dev/null | head -n 1 | cut -d ' ' -f 2 | sed 's/^.//')"
    install_hashicorp_app "terraform"
    readonly TERRAFORM_VERSION_NEW="$(terraform -v 2> /dev/null | head -n 1 | cut -d ' ' -f 2 | sed 's/^.//')"

    # Install vagrant
    echo "Installing vagrant"
    readonly VAGRANT_VERSION_OLD="$(vagrant -v 2> /dev/null | cut -d ' ' -f 2)"
    install_hashicorp_app "vagrant"
    readonly VAGRANT_VERSION_NEW="$(vagrant -v 2> /dev/null | cut -d ' ' -f 2)"

    # Report
    echo
    echo_info "Update completed"
}

main
