#!/usr/bin/env bash

set -Eeu
trap 'echo "Error: ${SCRIPT} - Function: ${FUNCNAME:-global context} - Line: ${LINENO} - Status: ${?}"' ERR

# Arguments
# shellcheck disable=SC2155
readonly SCRIPT=$(basename "${0}")

echo_info()
{
    echo -e "\e[0;36m${*}\e[0m"
}

check_bin()
{
    if ! command -v "${1}" &> /dev/null; then
        echo_error "Error: \"${1}\" is required but not installed."
        exit 1
    fi
}

main()
{
    check_bin python3

    if [ "$(uname -s)" != "Darwin" ]; then
        USER_OPTION="--user"
    fi

    local PACKAGES
    PACKAGES="$(python3 -m pip list --outdated ${USER_OPTION} --format=freeze)"

    if [ -n "${PACKAGES}" ]; then
        PACKAGES="$(echo "${PACKAGES}" | grep -v '^\-e' | cut -d = -f 1)"

        for PACKAGE in ${PACKAGES}; do
            echo_info "Updating ${PACKAGE}"
            python3 -m pip install --upgrade ${USER_OPTION} "${PACKAGE}"
        done

        echo_info "Done"
    else
        echo_info "All packages are already at the latest version"
    fi
}

main
