#!/usr/bin/env bash

# shellcheck disable=SC2155

set -Eeuo pipefail
trap 'print_error ${BASH_SOURCE[0]} ${LINENO} ${?}' ERR

# Arguments
readonly SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"

# Settings
readonly BASH_COMPLETION_DIR="${HOME}/dev/data/bash/completion"
readonly BASH_COMPLETIONS="helm kubectl"

echo_info()
{
    echo "$(tput setaf 6)${*}$(tput sgr0)"
}

echo_error()
{
    echo "$(tput setaf 1)${*}$(tput sgr0)"
}

print_error()
{
    local -r SOURCE_PATH="${1}"
    local -r LINE_NUMBER="${2}"
    local -r EXIT_STATUS="${3}"
    local -r CONTEXT_LINES="3"
    local -r SOURCE_CODE="$(pr -tn "${SOURCE_PATH}")"

    local RELATIVE_PATH="${SOURCE_PATH#"${SCRIPT_DIR}"}"
    local -r RELATIVE_PATH="${RELATIVE_PATH#/}"

    echo
    echo_error "$(tput bold)Error: command exited with status ${EXIT_STATUS} at ${RELATIVE_PATH}:${LINE_NUMBER}"

    tail -n +$((LINE_NUMBER - CONTEXT_LINES)) <<< "${SOURCE_CODE}" | head -n ${CONTEXT_LINES}
    echo_error "$(tput bold)$(tail -n +$((LINE_NUMBER)) <<< "${SOURCE_CODE}" | head -n 1)"
    tail -n +$((LINE_NUMBER + 1)) <<< "${SOURCE_CODE}" | head -n ${CONTEXT_LINES}
    echo

    exit 1
}

check_bin()
{
    if ! command -v "${1}" &> /dev/null; then
        echo_error "Error: \"${1}\" not found."
        exit 1
    fi
}

main()
{
    echo
    echo_info "Generating bash completions"

    if [ ! -d "${BASH_COMPLETION_DIR}" ]; then
        mkdir -p "${BASH_COMPLETION_DIR}"
    fi

    rm -f "${BASH_COMPLETION_DIR}"/*

    for COMPLETION in ${BASH_COMPLETIONS}; do
        echo "Generating ${COMPLETION} completion"
        check_bin "${COMPLETION}"
        ${COMPLETION} completion bash > "${BASH_COMPLETION_DIR}/${COMPLETION}"
    done

    echo "Generating jfrog completion"
    check_bin jfrog
    export JFROG_CLI_HOME_DIR="${BASH_COMPLETION_DIR}"
    jfrog completion bash > /dev/null

    echo "Generating pip3 completion"
    check_bin pip3
    pip3 completion --bash > "${BASH_COMPLETION_DIR}/pip3"

    echo "Generating npm completion"
    check_bin npm
    npm completion > "${BASH_COMPLETION_DIR}/npm"

    echo "Generating yq completion"
    check_bin yq
    yq shell-completion bash > "${BASH_COMPLETION_DIR}/yq"

    echo_info "Operation completed"
    echo
}

main
