#!/usr/bin/env bash

set -Eeuo pipefail
trap 'echo_error "\e[1mError: program exited with status ${?} at line ${LINENO}"' ERR

# Settings
readonly BASH_COMPLETION_DIR="${HOME}/dev/data/bash/completion"

echo_error()
{
    echo -e "\e[0;31m${*}\e[0m"
}

check_bin()
{
    if ! command -v "${1}" &> /dev/null; then
        echo_error "Error: \"${1}\" is required but not installed."
        exit 1
    fi
}

echo_generate()
{
    echo "Generate bash completion: ${*}"
}

main()
{
    if [ ! -d "${BASH_COMPLETION_DIR}" ]; then
        mkdir -p "${BASH_COMPLETION_DIR}"
    fi

    rm -rf "${BASH_COMPLETION_DIR:?}"/*

    echo_generate helm
    check_bin helm
    helm completion bash > "${BASH_COMPLETION_DIR}/helm"

    echo_generate kubectl
    check_bin kubectl
    kubectl completion bash > "${BASH_COMPLETION_DIR}/kubectl"

    echo_generate kubectl krew
    check_bin kubectl-krew
    kubectl krew completion bash > "${BASH_COMPLETION_DIR}/kubectl-krew"

    echo_generate npm
    check_bin npm
    npm completion > "${BASH_COMPLETION_DIR}/npm"

    echo_generate pip
    check_bin pip
    pip completion --bash > "${BASH_COMPLETION_DIR}/pip"

    echo_generate pip3
    check_bin pip3
    pip3 completion --bash > "${BASH_COMPLETION_DIR}/pip3"

    echo_generate yq
    check_bin yq
    yq shell-completion bash > "${BASH_COMPLETION_DIR}/yq"
}

main
