#!/usr/bin/env bash

set -Eeu
trap 'echo "Error: ${SCRIPT} - Function: ${FUNCNAME:-global context} - Line: ${LINENO} - Status: ${?}"' ERR
trap 'rm -rf ${TEMP_DIR}' EXIT

# Arguments
# shellcheck disable=SC2155
readonly SCRIPT=$(basename "${0}")

# Settings
readonly BIN_DIR="${HOME}/dev/bin"
readonly TEMP_DIR="/tmp/${SCRIPT}"
readonly OS="linux"
readonly ARCH_1="amd64"
readonly ARCH_2="x86_64"
readonly ARCH_3="64bit"
readonly ARCH_4="musl"

echo_error()
{
    echo -e "\e[0;31m${*}\e[0m"
}

check_bin()
{
    if ! command -v "${1}" &> /dev/null; then
        echo_error "Error: \"${1}\" is required but not installed."
        exit 1
    fi
}

get_version()
{
    local -r BIN_NAME="${1}"
    local -r RAW_VERSION=$(
        ${BIN_NAME} -v 2> /dev/null ||
        ${BIN_NAME} version 2> /dev/null ||
        ${BIN_NAME} --version 2> /dev/null ||
        true
    )

    echo "${RAW_VERSION}" \
        | grep -oE '(0|[1-9][[:digit:]]*)\.(0|[1-9][[:digit:]]*)(\.(0|[1-9][[:digit:]]*))?' \
        | head -n 1 \
        || true
}

print_version()
{
    local OLD_VERSION=${1:-}
    local NEW_VERSION=${2:-}

    if [ -z "${OLD_VERSION}" ]; then
        OLD_VERSION="none"
    fi

    if [ -z "${NEW_VERSION}" ]; then
        NEW_VERSION="error getting the new version"
    fi

    if [ "${OLD_VERSION}" = "${NEW_VERSION}" ]; then
        echo -e "Already at newest version: \e[0;32m${NEW_VERSION}\e[0m"
    else
        echo -e "Version updated: \e[0;33m${OLD_VERSION} -> ${NEW_VERSION}\e[0m"
    fi
}

get_github_url()
{
    local -r GITHUB_PATH="${1}"

    local -r URL=$(curl -fsSL "https://api.github.com/repos/${GITHUB_PATH}/releases/latest" |
        jq -r .assets[].browser_download_url |
        grep -iE "${OS}.*(${ARCH_1}|${ARCH_2}|${ARCH_3}|${ARCH_4})" |
        grep -vE '\.asc$|\.sig$|\.deb$|\.rpm$' |
        grep -vE 'tfsec-checkgen|hugo_extended'
    )

    echo "${URL}"
}

install_bin()
{
    local -r BIN_NAME="${1}"
    local -r URL="${2}"

    curl -fsSL "${URL}" -o "${BIN_DIR}/${BIN_NAME}"
    chmod +x "${BIN_DIR}/${BIN_NAME}"
}

install_archive()
{
    local -r ARCHIVE_TYPE="${1}"
    local -r BIN_NAME="${2}"
    local -r URL="${3}"
    local -r ARCHIVE_BIN_PATH="${4}"

    local -r ARCHIVE_PATH="${TEMP_DIR}/${BIN_NAME}.${ARCHIVE_TYPE}"

    case ${ARCHIVE_TYPE} in
        zip)
            local -r EXTRACT_CMD=(unzip -jqo "${ARCHIVE_PATH}" -d "${BIN_DIR}" "${ARCHIVE_BIN_PATH}")
            ;;
        tar.gz)
            local -r EXTRACT_CMD=(tar xzf "${ARCHIVE_PATH}" -C "${BIN_DIR}" "${ARCHIVE_BIN_PATH}" --transform 's|.*/||')
            ;;
        *)
            echo_error "Error: invalid archive type: ${ARCHIVE_TYPE}"
            exit 1
    esac

    curl -fsSL "${URL}" -o "${ARCHIVE_PATH}"
    # shellcheck disable=SC2068
    ${EXTRACT_CMD[@]}
    chmod +x "${BIN_DIR}/${BIN_NAME}"
    rm -f "${ARCHIVE_PATH}"
}

install_url_targz()
{
    local -r BIN_NAME="${1}"
    local -r DOWNLOAD_URL="${2}"
    local -r ARCHIVE_BIN_PATH="${3}"

    install_archive "tar.gz" "${BIN_NAME}" "${DOWNLOAD_URL}" "${ARCHIVE_BIN_PATH}"
}

install_github_bin()
{
    local -r BIN_NAME="${1}"
    local -r GITHUB_PATH="${2}"

    local -r DOWNLOAD_URL=$(get_github_url "${GITHUB_PATH}")

    install_bin "${BIN_NAME}" "${DOWNLOAD_URL}"
}

install_github_zip()
{
    local -r BIN_NAME="${1}"
    local -r GITHUB_PATH="${2}"
    local -r ARCHIVE_BIN_PATH="${3}"

    local -r DOWNLOAD_URL=$(get_github_url "${GITHUB_PATH}")

    install_archive "zip" "${BIN_NAME}" "${DOWNLOAD_URL}" "${ARCHIVE_BIN_PATH}"
}

install_github_targz()
{
    local -r BIN_NAME="${1}"
    local -r GITHUB_PATH="${2}"
    local -r ARCHIVE_BIN_PATH="${3}"

    local -r DOWNLOAD_URL=$(get_github_url "${GITHUB_PATH}")

    install_archive "tar.gz" "${BIN_NAME}" "${DOWNLOAD_URL}" "${ARCHIVE_BIN_PATH}"
}

install_app()
{
    local -r BIN_NAME="${1}"
    local -r INSTALL_TYPE="${2}"
    local -r URL="${3}"
    local -r ARCHIVE_BIN_PATH="${4}"

    echo "Install ${BIN_NAME}"

    local -r OLD_VERSION=$(get_version "${BIN_NAME}")

    # shellcheck disable=SC2086
    install_${INSTALL_TYPE} "${BIN_NAME}" "${URL}" "${ARCHIVE_BIN_PATH}"

    local -r NEW_VERSION=$(get_version "${BIN_NAME}")

    print_version "${OLD_VERSION}" "${NEW_VERSION}"
    echo
}

main()
{
    check_bin curl
    check_bin grep
    check_bin gzip
    check_bin jq
    check_bin tar
    check_bin unzip

    if [ ! -d "${BIN_DIR}" ]; then
        mkdir -p "${BIN_DIR}"
    fi

    if [ -d "${TEMP_DIR}" ]; then
        rm -rf "${TEMP_DIR}"
    fi

    mkdir -p "${TEMP_DIR}"

    local -r NCDU_URL="https://dev.yorhel.nl/download/ncdu-2.1-linux-x86_64.tar.gz"

    # Arguments  "binary"     "install type"   "github path or url"        "path in archive"
    install_app  "ctop"       "github_bin"     "bcicen/ctop"               ""
    install_app  "driftctl"   "github_bin"     "cloudskiff/driftctl"       ""
    install_app  "gitui"      "github_targz"   "extrawurst/gitui"          "./gitui"
    install_app  "hugo"       "github_targz"   "gohugoio/hugo"             "hugo"
    install_app  "terrascan"  "github_targz"   "accurics/terrascan"        "terrascan"
    install_app  "tflint"     "github_zip"     "terraform-linters/tflint"  "tflint"
    install_app  "tfsec"      "github_bin"     "aquasecurity/tfsec"        ""
    install_app  "ncdu"       "url_targz"      "${NCDU_URL}"               "ncdu"
}

main
