#!/usr/bin/env bash

# shellcheck disable=SC2155

set -Eeuo pipefail
trap 'print_error ${BASH_SOURCE[0]} ${LINENO} ${?}' ERR
trap 'print_report' EXIT

# Arguments
readonly SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"

# Settings
readonly TOOLS_DIR="${HOME}/dev/tools"
readonly TEMP_DIR="/tmp"

echo_info()
{
    echo "$(tput setaf 6)${*}$(tput sgr0)"
}

echo_error()
{
    echo "$(tput setaf 1)${*}$(tput sgr0)"
}

print_error()
{
    local -r SOURCE_PATH="${1}"
    local -r LINE_NUMBER="${2}"
    local -r EXIT_STATUS="${3}"
    local -r CONTEXT_LINES="3"
    local -r SOURCE_CODE="$(pr -tn "${SOURCE_PATH}")"

    local RELATIVE_PATH="${SOURCE_PATH#"${SCRIPT_DIR}"}"
    local -r RELATIVE_PATH="${RELATIVE_PATH#/}"

    echo
    echo_error "$(tput bold)Error: command exited with status ${EXIT_STATUS} at ${RELATIVE_PATH}:${LINE_NUMBER}"

    tail -n +$((LINE_NUMBER - CONTEXT_LINES)) <<< "${SOURCE_CODE}" | head -n ${CONTEXT_LINES}
    echo_error "$(tput bold)$(tail -n +$((LINE_NUMBER)) <<< "${SOURCE_CODE}" | head -n 1)"
    tail -n +$((LINE_NUMBER + 1)) <<< "${SOURCE_CODE}" | head -n ${CONTEXT_LINES}
    echo

    exit 1
}

check_bin()
{
    if ! command -v "${1}" &> /dev/null; then
        echo_error "Error: \"${1}\" is required but not installed."
        exit 1
    fi
}

install_targz()
{
    local -r URL="${1}"
    local -r TOOL_TAR_PATH="${2}"
    local -r TOOL_NAME="${3}"

    curl -sSL "${URL}" -o "${TEMP_DIR}/${TOOL_NAME}.tar.gz"
    rm -rf "${TEMP_DIR:?}/${TOOL_NAME}"
    mkdir -p "${TEMP_DIR}/${TOOL_NAME}"
    tar xzf "${TEMP_DIR}/${TOOL_NAME}.tar.gz" -C "${TEMP_DIR}/${TOOL_NAME}"
    rm -rf "${TOOLS_DIR:?}/${TOOL_NAME}"
    mv -f "${TEMP_DIR}/${TOOL_NAME}/${TOOL_TAR_PATH}" "${TOOLS_DIR}/${TOOL_NAME}"
    chmod +x "${TOOLS_DIR}/${TOOL_NAME}"
    rm -rf "${TEMP_DIR:?}/${TOOL_NAME}"
    rm -f "${TEMP_DIR}/${TOOL_NAME}.tar.gz"
}

print_version()
{
    local -r BIN=${1}
    local OLD_VERSION=${2}
    local NEW_VERSION=${3}

    if [ -z "${OLD_VERSION}" ]; then
        OLD_VERSION="None"
    fi

    if [ -z "${NEW_VERSION}" ]; then
        NEW_VERSION="Error getting the new version"
    fi

    if [ "${OLD_VERSION}" = "${NEW_VERSION}" ]; then
        echo "${BIN}: ${NEW_VERSION}"
    else
        echo "$(tput setaf 3)${BIN}: ${OLD_VERSION} -> ${NEW_VERSION}$(tput sgr0)"
    fi
}

print_report()
{
    {
        print_version "go" "${GO_VERSION_OLD}" "${GO_VERSION_NEW}"
    } | column -t -s ' '
    echo
}

main()
{
    check_bin curl
    check_bin tar

    if [ ! -d "${TOOLS_DIR}" ]; then
        mkdir -p "${TOOLS_DIR}"
    fi

    echo
    echo_info "Installing tools"

    # Install go
    echo "Installing go"
    readonly GO_VERSION_OLD="$(go version 2> /dev/null | cut -d ' ' -f 3 | sed 's/go//')"
    local -r GO_VERSION_LATEST="$(curl -sSL "https://golang.org/VERSION?m=text")"
    install_targz "https://dl.google.com/go/${GO_VERSION_LATEST}.linux-amd64.tar.gz" "go" "go"
    readonly GO_VERSION_NEW="$(go version 2> /dev/null | cut -d ' ' -f 3 | sed 's/go//')"

    # Report
    echo
    echo_info "Update completed"
}

main
