#!/usr/bin/env bash

set -Eeu
trap 'echo "Error: ${SCRIPT} - Function: ${FUNCNAME:-global context} - Line: ${LINENO} - Status: ${?}"' ERR
trap 'print_report' EXIT

# Arguments
# shellcheck disable=SC2155
readonly SCRIPT=$(basename "${0}")

# Settings
readonly TOOLS_DIR="${HOME}/dev/tools"
readonly TEMP_DIR="/tmp"

echo_info()
{
    echo -e "\e[0;36m${*}\e[0m"
}

echo_error()
{
    echo -e "\e[0;31m${*}\e[0m"
}

check_bin()
{
    if ! command -v "${1}" &> /dev/null; then
        echo_error "Error: \"${1}\" is required but not installed."
        exit 1
    fi
}

install_targz()
{
    local -r URL="${1}"
    local -r TOOL_TAR_PATH="${2}"
    local -r TOOL_NAME="${3}"

    curl -sSL "${URL}" -o "${TEMP_DIR}/${TOOL_NAME}.tar.gz"
    rm -rf "${TEMP_DIR:?}/${TOOL_NAME}"
    mkdir -p "${TEMP_DIR}/${TOOL_NAME}"
    tar xzf "${TEMP_DIR}/${TOOL_NAME}.tar.gz" -C "${TEMP_DIR}/${TOOL_NAME}"
    rm -rf "${TOOLS_DIR:?}/${TOOL_NAME}"
    mv -f "${TEMP_DIR}/${TOOL_NAME}/${TOOL_TAR_PATH}" "${TOOLS_DIR}/${TOOL_NAME}"
    chmod +x "${TOOLS_DIR}/${TOOL_NAME}"
    rm -rf "${TEMP_DIR:?}/${TOOL_NAME}"
    rm -f "${TEMP_DIR}/${TOOL_NAME}.tar.gz"
}

print_version()
{
    local -r BIN=${1}
    local OLD_VERSION=${2}
    local NEW_VERSION=${3}

    if [ -z "${OLD_VERSION}" ]; then
        OLD_VERSION="None"
    fi

    if [ -z "${NEW_VERSION}" ]; then
        NEW_VERSION="Error getting the new version"
    fi

    if [ "${OLD_VERSION}" = "${NEW_VERSION}" ]; then
        echo "${BIN}: ${NEW_VERSION}"
    else
        echo -e "\e[0;33m${BIN}: ${OLD_VERSION} -> ${NEW_VERSION}\e[0m"
    fi
}

print_report()
{
    {
        print_version "go" "${GO_VERSION_OLD}" "${GO_VERSION_NEW}"
    } | column -t -s ' '
    echo
}

main()
{
    check_bin curl
    check_bin tar

    if [ ! -d "${TOOLS_DIR}" ]; then
        mkdir -p "${TOOLS_DIR}"
    fi

    echo
    echo_info "Installing tools"

    # Install go
    echo "Installing go"
    # shellcheck disable=SC2155
    readonly GO_VERSION_OLD="$(go version 2> /dev/null | cut -d ' ' -f 3 | sed 's/go//')"
    local -r GO_VERSION_LATEST="$(curl -sSL "https://golang.org/VERSION?m=text")"
    install_targz "https://dl.google.com/go/${GO_VERSION_LATEST}.linux-amd64.tar.gz" "go" "go"
    # shellcheck disable=SC2155
    readonly GO_VERSION_NEW="$(go version 2> /dev/null | cut -d ' ' -f 3 | sed 's/go//')"

    # Report
    echo
    echo_info "Update completed"
}

main
