#!/usr/bin/env bash

#-----------------------------------------------------------------------------------------------------------------------

# Arguments
SCRIPT=$(basename "${0}")
DIRECTORY="${1:-.}"

#-----------------------------------------------------------------------------------------------------------------------

print_usage()
{
    echo
    echo "Usage:"
    echo
    echo "    ${SCRIPT}                Recursively clean the current directory from the DS_Store files"
    echo "    ${SCRIPT} <directory>    Recursively clean the specified directory from the DS_Store files"
    echo

    exit 1
}

#-----------------------------------------------------------------------------------------------------------------------

clean_ds()
{
    find "${DIRECTORY}" -name '.DS_Store' -type f -delete
}

#-----------------------------------------------------------------------------------------------------------------------

case ${DIRECTORY} in

    -h     | \
    --help )
        print_usage
        ;;

    *)
        clean_ds
        ;;

esac

#-----------------------------------------------------------------------------------------------------------------------
