#!/usr/bin/env bash

BASE_PATH="/System/Volumes/Data"

EXCLUDE_PATHS=(
    "Volumes"
    "usr/local/Homebrew"
    "mnt"
    ".DocumentRevisions-V100"
    ".PKInstallSandboxManager"
    ".PKInstallSandboxManager-SystemSoftware"
    ".Spotlight-V100"
    ".TemporaryItems"
    ".Trashes"
)

for EXCLUDE_PATH in ${EXCLUDE_PATHS[*]}; do
    EXCLUDE_ARGS="${EXCLUDE_ARGS} -path ${BASE_PATH}/${EXCLUDE_PATH} -o"
done

EXCLUDE_ARGS="${EXCLUDE_ARGS:: -3}"

# shellcheck disable=SC2086
sudo find ${BASE_PATH} -xdev \( ${EXCLUDE_ARGS} \) -prune -o -iname "*${1}*" -print | sed "s|^${BASE_PATH}||g"
